//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackofficeServerLib.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.ITransportadoraX")]
    public interface ITransportadoraX {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportadoraX/getBudget", ReplyAction="http://tempuri.org/ITransportadoraX/getBudgetResponse")]
        float getBudget(string fabAddress, string clientAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportadoraX/getAddress", ReplyAction="http://tempuri.org/ITransportadoraX/getAddressResponse")]
        string getAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransportadoraX/sendPackage", ReplyAction="http://tempuri.org/ITransportadoraX/sendPackageResponse")]
        void sendPackage(string fabAddress, string clientAddress, int idInFab);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransportadoraXChannel : BackofficeServerLib.ServiceReference4.ITransportadoraX, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransportadoraXClient : System.ServiceModel.ClientBase<BackofficeServerLib.ServiceReference4.ITransportadoraX>, BackofficeServerLib.ServiceReference4.ITransportadoraX {
        
        public TransportadoraXClient() {
        }
        
        public TransportadoraXClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransportadoraXClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportadoraXClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransportadoraXClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float getBudget(string fabAddress, string clientAddress) {
            return base.Channel.getBudget(fabAddress, clientAddress);
        }
        
        public string getAddress() {
            return base.Channel.getAddress();
        }
        
        public void sendPackage(string fabAddress, string clientAddress, int idInFab) {
            base.Channel.sendPackage(fabAddress, clientAddress, idInFab);
        }
    }
}
