//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackofficeServerLib.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IFabricanteC")]
    public interface IFabricanteC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteC/getAddress", ReplyAction="http://tempuri.org/IFabricanteC/getAddressResponse")]
        string getAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteC/getBudget", ReplyAction="http://tempuri.org/IFabricanteC/getBudgetResponse")]
        double getBudget();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteC/recordCd", ReplyAction="http://tempuri.org/IFabricanteC/recordCdResponse")]
        int recordCd(string artist, string[] tracks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFabricanteC/getCdStatus", ReplyAction="http://tempuri.org/IFabricanteC/getCdStatusResponse")]
        string getCdStatus(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFabricanteCChannel : BackofficeServerLib.ServiceReference3.IFabricanteC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FabricanteCClient : System.ServiceModel.ClientBase<BackofficeServerLib.ServiceReference3.IFabricanteC>, BackofficeServerLib.ServiceReference3.IFabricanteC {
        
        public FabricanteCClient() {
        }
        
        public FabricanteCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FabricanteCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricanteCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FabricanteCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAddress() {
            return base.Channel.getAddress();
        }
        
        public double getBudget() {
            return base.Channel.getBudget();
        }
        
        public int recordCd(string artist, string[] tracks) {
            return base.Channel.recordCd(artist, tracks);
        }
        
        public string getCdStatus(int id) {
            return base.Channel.getCdStatus(id);
        }
    }
}
